### ISSUE TITLE
Update repo and crates.io to note that this is unsafe

### ISSUE THREAD

**Issue by lilyball** [arcnmx/thread-scoped-rs#5]
This repository is a stable fork of an unsafe API. I understand why it was created at the time, but it was never updated to indicate that this API has a memory safety hole and that there are alternative crates that provide safe versions.

I think both the README for this repo as well as the description on crates.io should be updated accordingly, to warn people that they should not be introducing new dependencies on this crate.

**Comment by arcnmx** [comment]
Well it is in the documentation and code, but agreed on clarifying this in both readme and description. I haven't been paying attention for the past while, what's the current flavour for alternative crates to be listed as alternatives? Still crossbeam? (I recall there being a compiler bug at the time that prevented it from exposing a stable scoped interface?)

**Comment by lilyball** [comment]
:+1:

I think Crossbeam is good for low-level stuff, though I haven't watched it for a while. I think Rayon is good for higher-level parallelism. And there's a few crates that just expose scoped thread pools (safely) as well, such as scoped_threadpool, though I've never used them myself so I don't know if they're the "recommended" approach.

**Comment by arcnmx** [comment]
Cool, added rayon to the list. I wasn't sure about adding `scoped_threadpool` due to the nature of the API revolving around pools, and it doesn't seem to be actively maintained. The two current alternatives seem good to me, one direct replacement and one higher level / convenient one! If you have any other suggestions feel free to throw in a PR.
